# Generated by Django 4.1.4 on 2023-02-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
            ],
        ),
    ]
