# Generated by Django 4.1.4 on 2023-02-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_designation', models.CharField(max_length=50)),
                ('emp_salary', models.IntegerField()),
                ('emp_country', models.CharField(max_length=20)),
                ('emp_state', models.CharField(max_length=30)),
                ('emp_city', models.CharField(max_length=30)),
            ],
        ),
    ]
